# Generated by Django 5.2.17 on 2026-08-22 17:00

import church.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('full_name', models.CharField(max_length=200, verbose_name='nom complet')),
                ('role', models.CharField(max_length=150, verbose_name='fonction')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('short_biography', models.TextField(blank=True, verbose_name='courte biographie')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Leadership',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('denomination', models.CharField(default='ECC/56è CECC', max_length=120)),
                ('church_name', models.CharField(default='Centre Missionnaire Shimekah', max_length=200)),
                ('short_name', models.CharField(blank=True, default='CMS Shimekah', max_length=80)),
                ('founded_date', models.DateField(verbose_name='date de fondation')),
                ('description', models.TextField(blank=True)),
                ('mission_statement', models.TextField(blank=True, verbose_name='déclaration de mission')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location_reference', models.CharField(blank=True, max_length=255, verbose_name='référence géographique')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=30, verbose_name='téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='téléphone secondaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='church/')),
                ('youtube_url', models.URLField(blank=True, verbose_name='URL YouTube')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL Facebook')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='URL TikTok')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL Instagram')),
            ],
            options={
                'verbose_name': 'Church Settings',
                'verbose_name_plural': 'Church Settings',
            },
        ),
        migrations.CreateModel(
            name='ChurchStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('acronym', models.CharField(max_length=40, verbose_name='acronyme')),
                ('name', models.CharField(max_length=255, verbose_name='nom complet')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='structures/')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': "Structure de l'église",
                'verbose_name_plural': "Structures de l'église",
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='heure de fin')),
                ('is_featured', models.BooleanField(default=False, verbose_name='à la une')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='image de couverture')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('is_featured', models.BooleanField(default=False, verbose_name='à la une')),
                ('is_published', models.BooleanField(default=False, verbose_name='publiée')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='abonné')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrit le')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('platform', models.CharField(choices=[('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('Other', 'Autre')], max_length=20)),
                ('name', models.CharField(help_text='Ex : cmshimekah', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Laisser vide si pas encore disponible.', verbose_name='URL')),
                ('icon_name', models.CharField(blank=True, help_text="Nom d'icône côté frontend", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField(help_text="Collez simplement l'URL YouTube de la vidéo.", validators=[church.models.validate_youtube_url], verbose_name='URL YouTube')),
                ('youtube_video_id', models.CharField(blank=True, editable=False, max_length=32, verbose_name='ID YouTube')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='date de publication')),
                ('is_featured', models.BooleanField(default=False, verbose_name='à la une')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('category', models.CharField(choices=[('LEADER', 'Vision du leader'), ('COLLABORATOR', 'Vision collaboratrice')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Point de vision',
                'verbose_name_plural': 'Points de vision',
                'ordering': ['category', 'display_order', 'id'],
            },
        ),
    ]
